main:
	g++ zad2.cpp ./mbedtls/library/md5.c ./mbedtls/library/platform_util.c -o zad2 -I./mbedtls/include
	nvcc zad3.cu ./mbedtls/library/md5.c ./mbedtls/library/platform_util.c -o zad3 -I./mbedtls/include -I./mbedtls/library